### ISSUE TITLE
Motor is not moving, servo not working

### ISSUE THREAD

**Issue by RioKJ21** [Reinbert/ros_esp32cam_diffdrive#3]

**Comment by Reinbert** [comment]
Hi @RioKJ21!

First of all, thanks for your interest in my software. 

What do you mean with "I got no results"?
I won't debug your code as I obviously don't have the same robot as you. And as a programmer, you need to figure out yourself where the problem is exactly. I can only help you if you can narrow down your problem. 

So I guess, the motor is not moving. Here's a list of what the problem might be:
- Is your microcontroller connected to Wifi?
- Are you sending messages to "/cmd_vel" topic?
- Does your microcontroller receive messages from "/cmd_vel"?
- Does the motor move wenn you set a speed manually?

Cheers, Reinbert
